# Generated by Django 3.2.8 on 2022-03-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4, verbose_name='Currency')),
                ('sub_id', models.CharField(max_length=64, verbose_name='ID')),
                ('interval', models.CharField(max_length=32, verbose_name='Interval')),
                ('price', models.BigIntegerField(max_length=1024, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=128, verbose_name='ID')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
