# Generated by Django 3.2.8 on 2022-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.BigIntegerField(verbose_name='Price'),
        ),
    ]
