# Generated by Django 3.2.8 on 2022-03-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_stripecustomer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='Name')),
                ('price_id', models.CharField(max_length=64, verbose_name='ID')),
                ('currency', models.CharField(max_length=4, verbose_name='Currency')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('interval', models.CharField(max_length=32, verbose_name='Interval')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.plan'),
        ),
    ]
