# Generated by Django 3.2.8 on 2022-03-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220328_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='ID'),
        ),
    ]
