# Generated by Django 3.2.8 on 2021-11-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211125_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='current_currency',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='prev_currency',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 12, 58, 28, 95831)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 12, 58, 28, 95831)),
        ),
    ]
