# Generated by Django 3.2.8 on 2021-12-23 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211125_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 11, 31, 33, 799667)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 11, 31, 33, 799667)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('BTC', 'BTC')], default='USD', max_length=3),
        ),
    ]
