# Generated by Django 3.2.8 on 2022-03-26 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 14, 30, 45, 696768)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 14, 30, 45, 696768)),
        ),
    ]
