# Generated by Django 3.2.8 on 2022-03-28 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220328_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 15, 6, 26, 430502)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 15, 6, 26, 430502)),
        ),
    ]
