# Generated by Django 3.2.8 on 2022-03-28 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220328_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 21, 11, 55, 848906)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 21, 11, 55, 848906)),
        ),
    ]
